# -*- coding: utf-8 -*-
"""etl_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGy9V2Eyd83q5w8jCawLLopXD2EFeB9-
"""

# ETL PIPELINE: REST COUNTRIES API
import requests
import pandas as pd
import logging
import os


# LOGGING CONFIGURATION
logging.getLogger().handlers.clear()

logging.basicConfig(
    filename="etl_pipeline.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


# EXTRACT FUNCTION
def extract_data(url):
    try:
        logging.info("Starting data extraction from API")

        headers = {"User-Agent": "etl-project/5.0"}

        response = requests.get(url, headers=headers, timeout=10)

        if response.status_code == 200:
            data = response.json()
            logging.info(f"Data extracted successfully. Records: {len(data)}")
            return data
        else:
            logging.error(f"API failed with status code {response.status_code}")
            print(response.text)
            return None

    except Exception as error:
        logging.error(f"❗Extraction error: {error}")
        return None


# TRANSFORM FUNCTION
def transform_data(data):
    try:
        logging.info("Starting transformation")

        df = pd.json_normalize(data)

        logging.info(f"Rows before cleaning: {len(df)}")

        # Select required columns safely
        dataset = ['name.common', 'region', 'population', 'area', 'capital']
        df = df[[col for col in dataset if col in df.columns]]

        # Rename columns
        df.columns = ['country', 'region', 'population', 'area', 'capital']

        # Fix capital (list → string)
        df['capital'] = df['capital'].apply(
            lambda x: x[0] if isinstance(x, list) and len(x) > 0 else "Unknown"
        )

        # Handle nulls
        df.fillna({
            'population': 0,
            'area': 0,
            'region': 'Unknown'
        }, inplace=True)

        # Remove duplicates
        df.drop_duplicates(inplace=True)

        logging.info(f"Rows after cleaning: {len(df)}")
        logging.info("Transformation completed")

        return df

    except Exception as error:
        logging.error(f"❗Transformation error: {error}")
        return None


# LOAD FUNCTION
def load_data(df):
    try:
        logging.info("Starting load process")

        df.to_csv("output.csv", index=False)
        df.to_parquet("output.parquet", index=False)

        logging.info("Data saved as CSV and Parquet")

    except Exception as error:
        logging.error(f"Loading error: {error}")


# MAIN ETL FUNCTION
def run_etl():
    API_URL = "https://restcountries.com/v3.1/all?fields=name,region,population,area,capital"

    data = extract_data(API_URL)

    if data:
        print("\n Raw Extracted Data (First record):")
        print(data[:1])

        # create a temerory dataframe for info
        temp_df = pd.json_normalize(data)

        print(temp_df.isnull().sum())

        print("\n Shape:", temp_df.shape)

        print("\n Data Types After Extraction:")
        print(temp_df.dtypes)

        print("\n Data Info:")
        temp_df.info()

        print("\n Capital Column Value Types:")
        print(temp_df['capital'].apply(type).value_counts())

        print("\n Region Column Value Types:")
        print(temp_df['region'].apply(type).value_counts())

        df = transform_data(data)

        if df is not None:
            load_data(df)

            # File size comparison
            print("\n File Sizes:")
            print("CSV:", os.path.getsize("output.csv"), "bytes")
            print("Parquet:", os.path.getsize("output.parquet"), "bytes")

            print("\n✅ ETL Pipeline executed successfully!")
        else:
            print("\n❗Transformation failed")
    else:
        print("\n❗ Extraction failed")


# EXECUTE
if __name__ == "__main__":
    run_etl()

with open("etl_pipeline.log", "r") as file:
    print(file.read())

import pandas as pd
df = pd.read_csv("output.csv")
df